quarkus.datasource.db-kind=oracle
quarkus.datasource.username=567548
quarkus.datasource.password=130905
quarkus.datasource.jdbc.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL

quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=true

quarkus.http.port=8080

quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization