#Qualquer duvida analizar o README
# CORS
quarkus.http.cors=true

# Permite seu React local
quarkus.http.cors.origins=http://localhost:5173

# Métodos permitidos
quarkus.http.cors.methods=GET,PUT,POST,DELETE,OPTIONS

# Headers permitidos
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with

# Permite credenciais (caso use sessão ou token futuramente)
quarkus.http.cors.access-control-allow-credentials=true